name: worbbing
description: A new Flutter project.
publish_to: "none"

# 2024.6.14 -> 1.0.0+10
version: 1.0.0+10

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation:
  shared_preferences:
  url_launcher:
  google_fonts:
  sqflite:
  rive:
  flutter_local_notifications:
  device_info_plus:
  intl:
  timezone:
  flutter_app_badger:
  android_intent_plus:
  receive_sharing_intent:
  flutter_animate:
  envied:
  uuid:
  google_generative_ai:
  dio:
  rive_animated_icon:
  app_settings:
  auto_size_text:
  lottie:
  flutter_svg:
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  flutter_gen_runner:
  build_runner:
  json_serializable:
  flutter_launcher_icons:
  riverpod_generator:
  envied_generator:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/
    - assets/lottie/
    - assets/svg/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/worbbing_icon_ios.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/worbbing_icon_ios.png"
