name: worbbing
description: worbbing.
publish_to: "none"

version: 2.0.0+4

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  json_annotation:
  shared_preferences:
  url_launcher:
  google_fonts:
  sqflite:
  flutter_local_notifications:
  device_info_plus:
  intl:
  timezone:
  flutter_animate:
  envied:
  uuid:
  dio:
  rive_animated_icon:
  app_settings:
  auto_size_text:
  lottie:
  flutter_svg:
  package_info_plus:
  google_mobile_ads:
  app_tracking_transparency:
  flutter_sharing_intent:
  go_router:
  riverpod_annotation:
  hooks_riverpod:
  path:
  flutter_hooks: ^0.20.5
  flutter_timezone: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:
  json_serializable:
  flutter_launcher_icons:
  envied_generator:
  riverpod_generator:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/
    - assets/lottie/
    - assets/svg/

  fonts:
    - family: SawarabiGothic
      fonts:
        - asset: assets/fonts/Sawarabi_Gothic/SawarabiGothic-Regular.ttf

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/worbbing_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/worbbing_icon.png"
